name: Git auto

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Executing server update
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PRODUCTION_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/${{ secrets.PRODUCTION_DIRECTORY }}
          sudo git status
          sudo git checkout .
          sudo git clean -f
          sudo git checkout master
          sudo git pull
          sudo composer install --ignore-platform-reqs
          sudo php artisan config:clear
          sudo php artisan cache:clear
          sudo composer dump-autoload
          sudo php artisan migrate
          sudo php artisan routine:migrate
          sudo chown -R apache:apache public
          sudo chown -R apache:apache storage
          sudo chmod -R 777 config/database.php
          sudo php artisan config:clear
          sudo php artisan cache:clear
          sudo php artisan view:clear
          sudo supervisorctl restart all
